[package]
name = "word-compare-svc"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
actix-files = "0.6"
ndarray = "0.15"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.phf]
version = "0.10"
features = ["macros"]